### ISSUE TITLE
Route syntaxes

### ISSUE THREAD

**Issue by jenstornell** [jenstornell/kirby-secrets#6]
## In the config `c::set('routes')`

```php
c::set('routes', array(
  array(
    'pattern' => 'my/awesome/(:any)',
    'action'  => function($uid) {
      echo $uid;
    }
  )
));
```

https://getkirby.com/docs/developer-guide/advanced/routing

## In a plugin `kirby()->routes()`

```php
kirby()->routes(array(
  array(
    'pattern' => 'my/awesome/(:any)',
    'action'  => function($uid) {
      echo $uid;
    }
  )
));
```

I prefer this version most of the times.

## Consistant with registry `$kirby->set('route')`

```php
$kirby->set('route', array(
  'pattern' => 'my/awesome/(:any)',
  'action'  => function($uid) {
    echo $uid;
  }
));
```

## Internal use `$router->register()`

In most cases you probably will not need this syntax. Therefor I will not add an example of it here.

https://getkirby.com/docs/developer-guide/toolkit/routing

**Comment by lukasbestle** [comment]
Don't use `$router->register()`, it is an internal method and shouldn't be called from the outside. All other three variants are fine.

**Comment by jenstornell** [comment]
@lukasbestle While you are probably correct about that I find it strange that it's so well documented if it's not ment to be used outside the core:

https://getkirby.com/docs/developer-guide/toolkit/routing

I also find it strange that `kirby()->routes()` is not in the documentation at all. I use that all the time.

**Comment by lukasbestle** [comment]
It is meant to be used outside the core, but only if you use the Toolkit without the core (and create your own router instance). It's part of the Toolkit docs after all. :)

**Comment by jenstornell** [comment]
Ahh, I see. It's crystal clear now. =) Thanks!
